### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add a div to the HTML
- [x] Add a car image to the div container 
- [x] Style the background 
- [x] Style the car to make size appropriate 
- [x] Ensure that the page looks nice on desktop screen
- [x] Clean up all unnecessary styling. 
- [x] Fix all errors.
