### ISSUE TITLE
User can choose their car 

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/driving-game#11]
## 💰 Motivation

The user needs to choose which style of car they want.

## 📐 Plan

Give user choice of 3-4 top-down images cars on the page.

## ✅ Task List

- [x] Create a div 
- [x] Create a title that says: 'Choose your car' 
- [x] Provide at least 3 cars for the user to choose 
- [x] Create a querySelector for all the cars
- [x] Add an event listener for the cars. 
- [x] If user clicks on the car, then hide the rest of the cars
- [x] Create a CSS class for hiding cars and the display
- [x] Hide the 'choose your car' text
- [x] Set the chosen car to the variable $car 
- [x] Test to see that the game works with the chosen car 
- [x] Remove unnecessary styling of the cars
