### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a CSS class for car facing north 
- [x] Create a CSS class for car facing south 
- [x] Create a CSS class for car facing east
- [x] Create a CSS class for car facing west
- [x] Use query selector to target the car. 
- [x] Create a simple data model for the car with a property of direction.  
- [x] Create an event listener in the window for when the user presses the arrow keys
     - [x] If left arrow key is pressed --> change car direction to west
     - [x] If right arrow key is pressed --> car direction to east 
     - [x] If down arrow key is pressed --> car direction is south
     - [x] If up arrow key is pressed --> car direction is north 
- [x] Change car image class to be same as car.direction 
- [x] Make sure it looks good in the browser
- [x] Test for errors
