### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add location to data model to add x & y coordinates on page.
- [x] Absolutely position the image. 
- [x] Update event listener for the "space" key. 
- [x] Begin timer when space key is pressed.
- [x] Set timer to update every 16 milliseconds
- [x] Update location in the data model & increment values when space is pressed.
- [x] Use style property of element object to change car's top & left box offset properties when space key is pressed based on data model.
- [x] Test the code.
