### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Create a boolean to data model to assess if the car has started or not. 
- [x] If the boolean is true then call the move car function. 
- [x] Change the boolean to "false" for next time user clicks space.
- [x] If the boolean is false then stop the interval timer.
- [x] Change the boolean to "true" for next time user clicks space.
- [x] Test to make sure that the location coordinates stopped moving.
