### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Update the timer function with the following conditions:
- [x] If the car.direction is right, then the x-coordinates of the car need to increase. Y-coordinates stay the same.
- [x] If the car.direction is left, then the x-coordinates of the car need to decrease. Y-coordinates stay the same.
- [x] If the car.direction is up, then the y-coordinates of the car need to decrease.  X-coordinates stay the same.
- [x] If the car.direction is down, then the y-coordinates of the car need to increase. X-coordinates stay the same.
- [x] Test the car's movements to make sure it is registering each key & movement. 
- [x] Adjust styling of the car if necessary.
